### ISSUE TITLE
React to the button when it is connected or disconnected.

### ISSUE THREAD

**Issue by joselcv** [DarkerWaters/flic_button#14]
Bro, is there any way to react when the Flic button connects or disconnects? Something like having a listener to know if the button connects or disconnects, as it would be very useful to react to those states.

**Comment by butterbrain** [comment]
Unfortunately, I don't think that's something I can do. The Flic2 API
doesn't offer anything explicitly like that. I could do a polling timer to
keep checking the connectivity but I don't think that would work.

The seeming idea behind the flic2 is that, to preserve battery, it goes
quiet and disconnects fairly regularly. However, it isn't out of range, so
it isn't really disconnected - merely dormant. Because, when you press a
button, it quickly finds it, connects, sends the button press and responds.
So, while the coder thinks the button is sleeping and disconnected, it
doesn't appear to be to the user?

It's a nice solution that keeps the button working but the battery
long-lasting.

You could, in theory, extend the 'autoDisconnectTime' to something very
long and keep polling the button, one every 20 seconds or so, to see if it
responds with something simple - like the battery level. If it doesn't then
it can't be found and you can tell the user it's 'disconnected'? This would
really hurt the battery life though and the button might not even let you?

from the API
'A value of 511 means infinite. Otherwise, the button will automatically
disconnect after the specified number of seconds.'
https://javadoc.io/doc/io.flic/flic2lib-android/latest/index.html
under 'setAutoDisconnectTime'

This seems to suggest that you can keep the button active forever and
periodically call a 'get' on the button and see what happens?

However, it doesn't look like it's something they offer on the iOS API so
would be an android only operation )O:

The solution would be to write a connection in Flutter direct using GATT
over BLE and bypass the provided APIs.
https://github.com/50ButtonsEach/flic2-documentation/wiki/Flic-2-Protocol-Specification
Seems like a lot of work tho and is anyone really interested? I don't think
my plugin gets a lot of users...
